### ISSUE TITLE
 No longer supports installation by channe

### ISSUE THREAD

**Issue by iamjpsharma** [tm01013/how-to-make-your-own-crypto#10]
[!] Installation required, do you want to countinue? (y/n):
y
Downloading tools this will take some time...

Installing solana cli...

Error: No longer supports installation by channel. Please specify a release version as vX.Y.Z or install from https://release.anza.xyz.
────────────────[ERROR]────────────────

**Comment by LinusGeffarth** [comment]
Seeing this too on MacBook with macOS 15.1.1
