### ISSUE TITLE
Error: Program(InvalidAccountData)

### ISSUE THREAD

**Issue by emaborsa** [tm01013/how-to-make-your-own-crypto#6]
I am doing some tests, when I try to ```bash solana-token-creator.sh --edit-metadata-mode``` I always get `Error: Program(InvalidAccountData)`.

**Comment by tm01013** [comment]
Make shure you provideing the correct token mint address and field name. If you closed the mint you might not be able to update the metadata. If you created your token outside my token creator make sure you created with the —enable-metadata flag and then initialized the metadata.

**Comment by emaborsa** [comment]
I am no really sure, I used your tool:

```
Do you want to disable mint? (y/n):
It's required for every token to function correctly.
y
|------------------------!!WARNING!!-------------------------|
| If you disable mint you cannot get any more of your token! |
| And you cannot update the metadata!                        |
| Please check everithing is correct before countinue!       |
|------------------------------------------------------------|

Do you want to countinue? (y/n):
n

You're done!! 🎉 Congratulations you've created a crypo!! 🎉
```

Theoretically I did not closed the mint. How can I check if it is closed?

Anyway, using `bash solana-token-creator.sh --edit-metadata-mode` allows me to edit the fields previously defined IV.3, right?

**Comment by tm01013** [comment]
But to completly change the metadata you also need to update the off-chain metadata, becouse some programs display the off-chain some use the on-chain. And also **It's a best practise to keep bouth of them the same**, becouse comperaing them is used for metadata verification.
